/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    E_Add: typeof import('./src/components/Nodes/e_Add.vue')['default']
    E_FlieUpload: typeof import('./src/components/Nodes/e_FlieUpload.vue')['default']
    E_Output: typeof import('./src/components/Nodes/e_Output.vue')['default']
    E_Predict: typeof import('./src/components/Nodes/e_Predict.vue')['default']
    E_Start: typeof import('./src/components/Nodes/e_Start.vue')['default']
    E_Sub: typeof import('./src/components/Nodes/e_Sub.vue')['default']
    E_ViewImg: typeof import('./src/components/Nodes/e_ViewImg.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InputNode: typeof import('./src/components/Nodes/InputNode.vue')['default']
    MainGraph: typeof import('./src/components/MainGraph.vue')['default']
    NodePanel: typeof import('./src/components/NodePanel.vue')['default']
    OutputNode: typeof import('./src/components/Nodes/OutputNode.vue')['default']
  }
}
